CREATE TABLE IF NOT EXISTS OBJECTS (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DOUBLE,
    image_path VARCHAR(255),
    column_for_calc_the_score VARCHAR(255),
    quantity INT DEFAULT 0,
    user_id CHAR(36),
    score DOUBLE DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE SET NULL
)
