CREATE TABLE IF NOT EXISTS OBJECT_PROJECT (
    object_id VARCHAR(36) NOT NULL,
    project_id INT NOT NULL,
    PRIMARY KEY (object_id, project_id),
    FOREIGN KEY (object_id) REFERENCES OBJECTS(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE
);