CREATE TABLE IF NOT EXISTS OBJECT_ORDER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    object_id VARCHAR(36) NOT NULL,
    order_id VARCHAR(36) NOT NULL,
    amount INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (object_id) REFERENCES OBJECTS(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE
)
