CREATE TABLE IF NOT EXISTS PROJECT_STEP (
    project_id INT NOT NULL,
    step_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (project_id, step_id),
    FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE,
    FOREIGN KEY (step_id) REFERENCES STEPS(id) ON DELETE CASCADE
);