CREATE TABLE IF NOT EXISTS OBJECT_USER (
    object_id VARCHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    PRIMARY KEY (object_id, user_id),
    FOREIGN KEY (object_id) REFERENCES OBJECTS(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);