CREATE TABLE IF NOT EXISTS ORDER_DELIVERY_METHOD (
    order_id VARCHAR(36) NOT NULL,
    delivery_method_id INT NOT NULL,
    price DOUBLE DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (order_id, delivery_method_id),
    FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE,
    FOREIGN KEY (delivery_method_id) REFERENCES DELIVERY_METHODS(id) ON DELETE CASCADE
)
