CREATE TABLE IF NOT EXISTS PACKAGES (
    id VARCHAR(36) PRIMARY KEY,
    weight INT,
    code VARCHAR(255),
    locker_id VARCHAR(36),
    order_id VARCHAR(36),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (locker_id) REFERENCES LOCKERS(id) ON DELETE SET NULL,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE SET NULL
)
