CREATE TABLE IF NOT EXISTS ACTIVITY_LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id CHAR(36) NOT NULL DEFAULT '',
    action VARCHAR(50) NOT NULL,
    entity VARCHAR(100) NOT NULL DEFAULT '',
    entity_id VARCHAR(100) NOT NULL DEFAULT '',
    detail VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
